### ISSUE TITLE
 the files in the OneDrive is not reachable

### ISSUE THREAD

**Issue by lintingguan** [HRNet/HRNet-Facial-Landmark-Detection#13] opened 2019-07-29 03:47 UTC
hi, i want try to download the trained weights and preprocessed files, but the file link of  OneDrive is not reachable, does anyone share the trained weights and preprocessed annotation files  with any other locations?

**Comment by LpfML** [comment] 2019-08-13 02:12
Did you download success now? I can not open the website too.

**Comment by wondervictor** [comment] 2019-08-13 08:46
@LpfML see

**Comment by wondervictor** [comment] 2019-08-13 08:47
Duplicate of #1

**Closed by wondervictor** 2019-08-13 08:47 UTC
